broadinstitute/terra-helm

.github/workflows/release.yaml

Added a new version of the chart-releaser-action which supports helm 3 charts.

Added chart releaser action and updated to support helm3

---

charts/terra-monitoring-setup/Chart.yaml
charts/terra-monitoring-setup/templates/namespace.yaml
charts/terra-stackdriver/templates/grafana-service.yaml
charts/terra-stackdriver/templates/prometheus-service.yaml

fix for accidentally deleting old charts that are released. Causes problems with cr.

Fix to issue with accidentally deleteing old charts and chart releaser

---

charts/terra-prometheus/Chart.lock
charts/terra-prometheus/Chart.yaml

Fogrgot to restore these files when adding back missing charts

Added missing content to chart files

---

charts/terra-ap-prometheus-operator/Chart.yaml
charts/terra-ap-prometheus-operator/values.yaml

Attempting fix to prometheus configs causing it to monitor only it's own namespace

Prom deploy

---

charts/terra-ap-prometheus-operator/Chart.yaml
charts/terra-ap-prometheus-operator/values.yaml

testing fix to prometheus not finding core k8s components

Possible fix to prometheus not discovering core k8s componenets

---

charts/cromwell/Chart.yaml
charts/cromwell/templates/_deployment.tpl

cc @cjllanwarne 
Going to merge and deploy this to dev shortly

DDO-400 Populate cromwell id with pod name

---

charts/terra-argocd-app/Chart.yaml
charts/terra-argocd-app/templates/app.yaml
charts/terra-argocd-app/templates/legacy-configs-app.yaml
charts/terra-argocd-app/values.yaml
charts/terra-argocd-env/Chart.yaml
charts/terra-argocd-env/templates/project.yaml
charts/terra-argocd-env/values.yaml
charts/terra-argocd-templates/Chart.yaml
charts/terra-argocd-templates/templates/_helpers.tpl

Replace `clusters` map in values with explicit values `clusterAddress` and `clusterName`

Changes to support rendering cluster resources in the terra-helmfile repo

---

charts/cert-manager/README.md

Fix incorrect cluster issuer reference in readme.

Fix readme error

---

charts/terra-argocd-app/Chart.yaml
charts/terra-argocd-app/templates/app.yaml
charts/terra-argocd-app/values.yaml

First step to enable auto-sync for workspace manager in dev.

DDO-476 Make it possible to pass in a sync policy to terra-argocd-app chart

---

charts/crljanitor/Chart.yaml
charts/crljanitor/README.md
charts/crljanitor/templates/_helpers.tpl
charts/crljanitor/templates/cert.yaml
charts/crljanitor/templates/deployment.yaml
charts/crljanitor/templates/proxy-apache-httpd-configmap.yaml
charts/crljanitor/templates/service.yaml
charts/crljanitor/values.yaml

- Added helm-docs annotations and generated README
- Added apache proxy for TLS

CRL Janitor Update

---

charts/cromwell/Chart.yaml
charts/cromwell/templates/_deployment.tpl
charts/cromwell/templates/deployments.yaml
charts/cromwell/values.yaml

* nest deployment configurations under new key `deployments`
* use global.applicationVersion instead of appVersion
* prefix container names with deployment name

Refactor cromwell chart

---

charts/ap-argocd-preinstall/Chart.yaml
charts/ap-argocd-preinstall/templates/certificate.yaml

Use cert-manager to provision tls cert for ArgoCD

DDO-365 cert-manager cert for ap-argocd instance

---

charts/crljanitor/Chart.yaml
charts/crljanitor/templates/deployment.yaml
charts/crljanitor/templates/secrets.yaml

New secrets stored in https://github.com/broadinstitute/terraform-ap-deployments/pull/66

CA-941 Add env secret for Stairway database in crl-janitor.

---

charts/terra-cluster/Chart.yaml
charts/terra-cluster/values.yaml

Update the terra-cluster chart to pick up a fix in the prometheus chart.

DDO-398 terra cluster dependency prometheus

---

charts/postgres/Chart.yaml
charts/postgres/README.md
charts/postgres/README.md.gotmpl
charts/postgres/templates/_container.yaml
charts/postgres/templates/_init-db-configmap.yaml
charts/postgres/values.yaml

[POC chart PR that uses this](https://github.com/broadinstitute/terra-helm/pull/86)

DDO-548 Add postgres library chart

---

charts/terra-argocd-app/Chart.yaml
charts/terra-argocd-app/README.md
charts/terra-argocd-app/templates/app.yaml
charts/terra-argocd-app/templates/legacy-configs-app.yaml
charts/terra-argocd-app/values.yaml

* Fix label bug, add some additional quoting for safety
* Helm-docs

DDO-545 Fix bug impacting label rendering in terra-argocd-app chart

---

charts/terra-argocd-env/Chart.yaml
charts/terra-argocd-env/README.md
charts/terra-argocd-env/templates/project.yaml
charts/terra-argocd-env/values.yaml

Related: https://github.com/broadinstitute/terra-helmfile/pull/71

Update Terra ArgoCD environment chart to support a project deploying to multiple clusters

---

charts/crljanitor/Chart.yaml
charts/crljanitor/templates/deployment.yaml

To be used in https://github.com/DataBiosphere/terra-resource-janitor/pull/36
https://github.com/census-instrumentation/opencensus-java/blob/5be70440b53815eec1ab59513390aadbcec5cc9c/contrib/resource_util/src/main/java/io/opencensus/contrib/resource/util/ContainerResource.java#L79
https://github.com/census-instrumentation/opencensus-java/blob/5be70440b53815eec1ab59513390aadbcec5cc9c/contrib/resource_util/src/main/java/io/opencensus/contrib/resource/util/K8sResource.java#L112

PF-3 Set container and namespace env variables from k8s metadata for stackdriver stats exporting

---

charts/workspacemanager/Chart.yaml
charts/workspacemanager/templates/deployment.yaml
charts/workspacemanager/values.yaml

[Main PR with description of changes](https://github.com/DataBiosphere/github-actions/pull/5)

DDO-604 Add DB initialization var to WSM

---

charts/leonardo/Chart.yaml
charts/leonardo/README.md
charts/leonardo/templates/_labels.tpl
charts/leonardo/templates/role.yaml
charts/leonardo/templates/roleBinding.yaml
charts/leonardo/templates/serviceAccount.yaml
charts/leonardo/values.yaml

First pass at a skeleton Leo chart the mimics the Cromwell chart's layout. Values specified, but not yet implemented.

DDO-660 Skeleton chart for Leonardo

---

charts/leonardo/Chart.yaml
charts/leonardo/templates/cronjob.yaml

https://broadworkbench.atlassian.net/browse/IA-2164

IA-2164  fix syntax error from previous PR

---

charts/ontology/Chart.yaml
charts/ontology/templates/deployment.yaml

Add a revision history limit to deployments. Not sure if this is the right place to add it, can't find much in the argo docs on it.

Add Revision History Limit

---

charts/leonardo/Chart.yaml
charts/leonardo/templates/cronjob.yaml
charts/leonardo/templates/zombieMonitorCron.yaml
charts/leonardo/values.yaml

https://broadworkbench.atlassian.net/browse/IA-2213

[IA-2213] mob changes. adds a zombie monitor yaml file

---

charts/rbs/Chart.yaml
charts/rbs/README.md
charts/rbs/templates/_helpers.tpl
charts/rbs/templates/cert.yaml
charts/rbs/templates/deployment.yaml
charts/rbs/templates/proxy-apache-httpd-configmap.yaml
charts/rbs/templates/role.yaml
charts/rbs/templates/rolebinding.yaml
charts/rbs/templates/secrets.yaml
charts/rbs/templates/service-account.yaml
charts/rbs/templates/service.yaml
charts/rbs/values.yaml

Tried using skaffold, it works:
https://rbs.yyu.integ.envs.broadinstitute.org/status

[PF-110] initial rbs helm chart

---

charts/workspacemanager/Chart.yaml
charts/workspacemanager/templates/deployment.yaml
charts/workspacemanager/values.yaml

Related:
https://github.com/DataBiosphere/terra-workspace-manager/pull/99
https://github.com/broadinstitute/terra-helmfile/pull/269

add some values for wsm

---

charts/rbs/templates/deployment.yaml

Related comment threads:
https://docs.google.com/document/d/1VfgL8D6PpJg7irbL_gKnmyZ5_GH5OYGfK8GPN45odUs/edit?disco=AAAAG95t27k
Spring variable name reference: https://github.com/DataBiosphere/terra-rbs/blob/master/src/main/resources/application.yml

[PF-112] Update environment var name to use spring auto environment variable

---

charts/leonardo/values.yaml

New version will include:
https://broadworkbench.atlassian.net/browse/IA-2232
https://broadworkbench.atlassian.net/browse/IA-2245

IA-2232 IA-2245 update zombie monitor

---

charts/leonardo/values.yaml

https://github.com/broadinstitute/leonardo-cron-jobs/pull/19

[no ticket] bump cron job versions

---

charts/leonardo/values.yaml

https://github.com/broadinstitute/leonardo-cron-jobs/pull/24
https://broadworkbench.atlassian.net/browse/IA-2312

IA-2312 bump leonardo cron jobs versions

---

charts/leonardo/values.yaml

https://github.com/broadinstitute/leonardo-cron-jobs/pull/26

[no ticket] fix config bug for resource-validator

---

charts/ontology/templates/_site.conf.tpl

Remove unnecessary site.conf configuration

Ontology: remove server name alias

---

charts/leonardo/templates/cronjob.yaml

I think we feel good enough about resource validator now that we can enable it for real

[no ticket] remove dryRun

---

charts/rawls/Chart.yaml
charts/rawls/README.md
charts/rawls/templates/_configmap.tpl
charts/rawls/templates/_deployment.tpl
charts/rawls/templates/_labels.tpl
charts/rawls/templates/_service.tpl
charts/rawls/templates/config/_prometheusJmx.yaml.tpl
charts/rawls/templates/deployments.yaml
charts/rawls/templates/ingress.yaml
charts/rawls/templates/ingressCert.yaml
charts/rawls/templates/podMonitor.yaml
charts/rawls/templates/role.yaml
charts/rawls/templates/roleBinding.yaml
charts/rawls/templates/serviceAccount.yaml
charts/rawls/values.yaml
release-strategy.json

Initial pr for the rawls helm chart

DDO-790 rawls k8s initial

---

charts/buffer/templates/secrets.yaml

Value from: https://github.com/broadinstitute/terraform-ap-deployments/blob/master/terra-env/vault_crl_janitor.tf#L85

[PF-232] fix janitor SA account path

---

charts/buffer/values.yaml

The github repo name is terra-resource-buffer:
https://github.com/DataBiosphere/terra-resource-buffer
And this should be the image name

[PF-232] fix RBS image name

---

charts/terra-cluster/Chart.yaml
charts/terra-cluster/values.yaml

[pr to update prometheus](https://github.com/broadinstitute/terra-helm/pull/208)﻿

DDO-835-1 Bump prometheus chart in terra-cluster

---

charts/agora/Chart.yaml
charts/agora/README.md
charts/agora/README.md.gotmpl
charts/cromiam/Chart.yaml
charts/cromiam/README.md
charts/cromiam/README.md.gotmpl

These will be used for setting up deployments for the initial poc.

Initial dummy charts for Agora and Cromiam

---

charts/workspacemanager/README.md
charts/workspacemanager/templates/deployment.yaml
charts/workspacemanager/values.yaml

The nested values cause issues when they are not present during rendering. flattened vars are recommended instead of nesting.
https://v2.helm.sh/docs/chart_best_practices/#flat-or-nested-values
broadinstitute/terra-helmfile#698

PF-153 Flatten WM folder and spend helm vars

---

charts/firecloudorch/Chart.yaml
charts/firecloudorch/README.md

Creates an empty chart for firecloud orchestration in order to perform
initial ci/cd setup for porting orchestration to k8s﻿

DDO-913 Orchestration k8s setup

---

charts/dsp-argocd/templates/apps/terra-app-generator.yaml

Fix typo introduced in https://github.com/broadinstitute/terra-helm/pull/226

DDO-915 Fix typo from #226

---

charts/sam/templates/deployment.yaml
charts/sam/values.yaml

- Point liveness probe to version endpoint
- Values syntax tweaks

Sam tweaks

---

charts/buffer/templates/deployment.yaml
charts/buffer/templates/proxy-apache-httpd-configmap.yaml
charts/buffer/templates/proxy-tcell-configmap.yaml
charts/buffer/templates/secrets.yaml
charts/buffer/values.yaml

- Added TCell config based on the way it is done for WM
- Added whitelisting for client SA
- Removed all the LDAP stuff (not 100% sure if this is right but I don't think Buffer uses/needs it?)

DDO-892 add client SA whitelisting and TCell to Buffer

---

charts/terra-cluster/Chart.yaml
charts/terra-cluster/values.yaml

This pr updates terra-cluster to use the new prometheus chart ﻿

DDO-919 Part-2 Update terra-cluster 

---

release-strategy.json

Helm version of [this WM PR](https://github.com/DataBiosphere/terra-workspace-manager/pull/173)

Put new WM chart versions on the release train

---

charts/cromiam/Chart.yaml
charts/cromiam/README.md
charts/cromiam/templates/_labels.tpl
charts/cromiam/templates/config/_prometheusJmx.yaml.tpl
charts/cromiam/templates/configmap.yaml
charts/cromiam/templates/deployment.yaml
charts/cromiam/templates/ingress.yaml
charts/cromiam/templates/ingress/backendconfig.yaml
charts/cromiam/templates/ingress/frontendconfig.yaml
charts/cromiam/templates/ingress/service.yaml
charts/cromiam/templates/podMonitor.yaml
charts/cromiam/templates/role.yaml
charts/cromiam/templates/roleBinding.yaml
charts/cromiam/templates/serviceAccount.yaml
charts/cromiam/values.yaml

Initial cromiam Helm chart implementation

DDO-945 First pass at cromiam Helm chart

---

charts/terra-cluster/Chart.yaml
charts/terra-cluster/values.yaml

bumping the version for the prometheus dependency in terra cluster and disabling the default kubernetes system alerts

DDO-1011 Part 2 terra-cluster  bump

---

charts/duos/Chart.yaml
charts/duos/templates/_config.json.tpl

Current configs for tag and hash are empty. This PR fixes that. Have tested in Argo on dev instance.

DUOS - Update config values

---

charts/duos/README.md
charts/duos/templates/_config.json.tpl
charts/duos/values.yaml

Add a new config we are using for the chairperson console
See also https://github.com/broadinstitute/terra-helmfile/pull/893

DUOS-966: Add new config to duos

---

charts/workspacemanager/templates/deployment.yaml
charts/workspacemanager/templates/secrets.yaml
charts/workspacemanager/values.yaml

Fields were removed in https://github.com/DataBiosphere/terra-workspace-manager/pull/215/files

Cleanup buffer.enabled and googleFolderId

---

charts/consent/Chart.yaml
charts/consent/templates/_consent.yaml.tpl
charts/ontology/Chart.yaml
charts/ontology/templates/_ontology.yaml.tpl

Update the app configs to log in json format. This requires two PRs in the apps to support this logging, do not merge until these are merged/deployed:
* https://github.com/DataBiosphere/consent/pull/925
* https://github.com/DataBiosphere/consent-ontology/pull/386
Addresses
* https://broadworkbench.atlassian.net/browse/DUOS-791
* https://broadworkbench.atlassian.net/browse/DUOS-1028

DUOS: Log in JSON Format

---

charts/terra-cluster/Chart.yaml
charts/terra-cluster/values.yaml

Adding the diskmanager dependency to terra-cluster in this pr to avoid version bumping conflicts﻿

DDO-1060 part 2 Add diskmanager to terra-cluster

---

charts/terra-cluster/Chart.yaml

Bump terra-cluster-storage dependency for https://github.com/broadinstitute/terra-helm/pull/284

DDO-992 bump terra-cluster chart

---

charts/filebeat/templates/config.yaml
charts/filebeat/templates/inputConfig.yaml

Previous pr put multiline handling in the wrong location. This pr should actually fix it.
- stacktrace handling?
- actual use multiline processing?

Actual fix to multiline stack trace handling

---

charts/mongodb/README.md
charts/mongodb/templates/expose.yaml
charts/mongodb/values.yaml

Add support for exposing MongoDB deployments outside the cluster.

DDO-1088 Expose MongoDB GKE deployment in dev

---

charts/leonardo/templates/deployments/_deployment.tpl

Bring over https://github.com/broadinstitute/firecloud-develop/pull/2426

IA-2397 show certs in set up chart directory as well 

---

charts/workspacemanager/templates/configmaps/tcell_configmap.yaml
charts/workspacemanager/templates/deployment.yaml
charts/workspacemanager/values.yaml

This is identical to [this pr](https://github.com/broadinstitute/terra-helm/pull/323) but applied to workspace manager instead of buffer.

DDO-1132 WSM fix Tcell in Apache Proxy

---

charts/mongodb/.helmignore
charts/mongodb/scripts/collectionCounts.js
charts/mongodb/scripts/mongo-dump.sh
charts/mongodb/scripts/mongo-import.sh

Commit MongoDB cutover scripts to Helm chart for the sake of posterity.

DDO-1130 Commit MongoDB cutover scripts

---

charts/leonardo/Chart.yaml
charts/leonardo/templates/janitorConfigMap.yaml
charts/leonardo/templates/janitorCron.yaml
charts/leonardo/values.yaml

[JIRA ticket](https://broadworkbench.atlassian.net/browse/IA-2228)
[Companion leonardo-cron-jobs PR](https://github.com/broadinstitute/leonardo-cron-jobs/pull/91)

[IA-2228] Add Janitor cron job for Leonardo

---

charts/leonardo/templates/cronjob.yaml
charts/leonardo/templates/janitorCron.yaml
charts/leonardo/templates/zombieMonitorCron.yaml
charts/leonardo/values.yaml

* add `enable` flag for all cron jobs
* reduce janitor frequency
Need https://github.com/broadinstitute/terra-helmfile/pull/1364 to go in first I think

IA-2818 add enable flag for all cron jobs

---

charts/cromiam/templates/deployment.yaml
charts/cromiam/values.yaml

Updating template to allow annnotations

* DDO-1259 Add annotation to Cromiam

---

charts/dsp-atlantis/templates/githubCredentials.yaml
charts/dsp-atlantis/values.yaml

token from vault into atlantis

DDO-1304 added githubCredentials.yaml to import github

---

charts/azurepoc/Chart.yaml
charts/azurepoc/README.md
charts/azurepoc/README.md.gotmpl
charts/azurepoc/templates/_labels.tpl
charts/azurepoc/templates/certificate.yaml
charts/azurepoc/templates/deployment.yaml
charts/azurepoc/templates/ingress.yaml
charts/azurepoc/templates/rbac.yaml
charts/azurepoc/templates/service.yaml
charts/azurepoc/values.yaml

This contains the helm chart for the azurepoc service. It is a helloworld spring boot app intended to be used to demo a pipeline for deploying to azure. However it is also good example of a relatively simple helm chart containing all the core resources needed to run a web service on kubernetes.

DDO-1272 Helm Chart for the Azure Deployment Pipeline POC App

---

charts/externalcreds/templates/deployment.yaml
charts/externalcreds/templates/secrets.yaml

See https://github.com/DataBiosphere/terra-external-credentials-manager/pull/16

client id for ecm swagger ui [POL-55]

---

charts/workspacemanager/README.md
charts/workspacemanager/templates/deployment.yaml
charts/workspacemanager/values.yaml

Set environment variables via the values file without having to edit the helm file

* DDO-1322 Populate env vars for Workspace manager

---

charts/externalcreds/README.md
charts/externalcreds/values.yaml

following https://github.com/DataBiosphere/terra-external-credentials-manager/pull/20

move ecm to broad-dsp-gcr-public

---

charts/agora/templates/deployment.yaml
charts/agora/values.yaml
charts/cromiam/templates/deployment.yaml
charts/cromiam/values.yaml
charts/cromwell/values.yaml
charts/firecloudorch/templates/deployment.yaml
charts/firecloudorch/values.yaml
charts/rawls/templates/_deployment.tpl
charts/rawls/values.yaml
charts/sam/templates/deployment.yaml
charts/sam/values.yaml
charts/thurloe/templates/deployment.yaml
charts/thurloe/values.yaml

Update image to newer tcell agent for apache.

*DD0-357 Upgrade to latest TCell webserver (for proxy)

---

charts/dsp-argocd/README.md
charts/dsp-argocd/templates/_labels.tpl
charts/dsp-argocd/templates/backendconfig.yaml
charts/dsp-argocd/templates/certificate.yaml
charts/dsp-argocd/templates/psp.yaml
charts/dsp-argocd/templates/role.yaml
charts/dsp-argocd/templates/roleBinding.yaml
charts/dsp-argocd/templates/secrets.yaml
charts/dsp-argocd/values.yaml

Upgrade to the image from this PR: https://github.com/broadinstitute/terra-helmfile-images/pull/18
And some chart cleanup:
* Use secrets-manager to manage Vault approle secret
* Use a template for labels

DDO-1410 ArgoCD image bump + cleanup

---

charts/sysbox/Chart.yaml
charts/sysbox/README.md
charts/sysbox/README.md.gotmpl
charts/sysbox/templates/_helpers.tpl
charts/sysbox/templates/psp.yaml
charts/sysbox/templates/role-binding.yaml
charts/sysbox/templates/role.yaml
charts/sysbox/templates/sysbox/_LICENSE
charts/sysbox/templates/sysbox/sysbox-deploy-k8s.yaml
charts/sysbox/templates/sysbox/sysbox-deploy-rbac.yaml
charts/sysbox/templates/sysbox/sysbox-runtimeclass.yaml

https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md#installation-of-sysbox but in a chart

[DDO-1424] add sysbox installation chart

---

charts/dsp-argocd/templates/apps/gha-runner.yaml
charts/dsp-argocd/templates/apps/sysbox.yaml
charts/dsp-argocd/templates/projects/dsp-ci.yaml
charts/dsp-argocd/values.yaml

Adds default as a dest on the dsp-ci project, puts sysbox there. Also moves the source directory for the existing ones to clean up.

[DDO-1424] Put sysbox on dsp-ci with argocd

---

charts/leonardo/README.md
charts/leonardo/templates/deployments/_deployment.tpl
charts/leonardo/values.yaml
charts/thurloe/README.md
charts/thurloe/templates/deployment.yaml
charts/thurloe/values.yaml

Adding 30-second sleep for leonardo and Thurloe to give the cloudsql proxy container time to startup.

* DDO-1352 Add 30-second sleep 

---

charts/dsp-argocd/values.yaml

[DDO-1424] bump sysbox version on argocd

---

charts/terra-cluster/Chart.yaml

version bump associated with #442

DDO-1430 Part 2 Bump prometheus in terra cluster

---

charts/thurloe/values.yaml

Specify 3 replicas per standards

*DDO-1429 bump replicas thurloe

---

charts/consent/README.md
charts/consent/templates/_consent.yaml.tpl
charts/consent/values.yaml

https://broadworkbench.atlassian.net/browse/DUOS-1356
See also: 
* https://github.com/broadinstitute/terra-helmfile/pull/1560
* https://github.com/DataBiosphere/consent/pull/1230

DUOS-1356: Add Sam url to consent configs

---

charts/agora/Chart.yaml
charts/agora/templates/ingress.yaml
charts/agora/values.yaml
charts/buffer/Chart.yaml
charts/buffer/templates/ingress/ingress.yaml
charts/consent/Chart.yaml
charts/consent/templates/ingress.yaml
charts/consent/values.yaml
charts/cromiam/Chart.yaml
charts/cromiam/templates/ingress.yaml
charts/externalcreds/Chart.yaml
charts/externalcreds/templates/ingress/ingress.yaml
charts/firecloudorch/Chart.yaml
charts/firecloudorch/templates/ingress/ingress.yaml
charts/firecloudui/Chart.yaml
charts/firecloudui/templates/ingress/ingress.yaml
charts/jobmanager/Chart.yaml
charts/jobmanager/templates/ingress.yaml
charts/leonardo/Chart.yaml
charts/rawls/Chart.yaml
charts/rawls/templates/ingress.yaml
charts/rawls/values.yaml
charts/thurloe/Chart.yaml
charts/thurloe/templates/ingress/ingress.yaml
charts/thurloe/values.yaml
charts/workspacemanager/Chart.yaml
charts/workspacemanager/templates/ingress/ingress.yaml

This reverts commit 89206c9bd1191e1a7b8466b06908b181c3f69f15.

Revert "* DDO-1468 Get apps to use ingress library for Ingress (#457)"

---

charts/consent/templates/deployment.yaml
charts/consent/values.yaml
charts/crljanitor/templates/deployment.yaml
charts/crljanitor/values.yaml
charts/cromwell/templates/_deployment.tpl
charts/cromwell/values.yaml
charts/externalcreds/templates/deployment.yaml
charts/externalcreds/values.yaml
charts/hydra/templates/deployment.yaml
charts/hydra/values.yaml
charts/leonardo/templates/deployments/_deployment.tpl
charts/rawls/templates/_deployment.tpl
charts/rawls/values.yaml
charts/sam/templates/deployment.yaml
charts/sam/values.yaml
charts/thurloe/templates/deployment.yaml
charts/workspacemanager/templates/deployment.yaml
charts/workspacemanager/values.yaml

Reverts broadinstitute/terra-helm#458

Revert "* DDO-1352 Add sleep to apps with cloudsql proxy"

---

charts/buffer/Chart.yaml
charts/buffer/templates/ingress/ingress.yaml

Refactor Buffer Ingress chart to use ingresslib
Env-dif [here](https://github.com/broadinstitute/terra-helmfile/pull/1621/checks?check_run_id=3487540841#step:8:2107)

* DDO-1468 Refactor Bufffer Ingress chart to use ingresslib

---

charts/ingresslib/templates/_ingress.yaml

This PR incorporates feedback from this [review comment](https://github.com/broadinstitute/terra-helm/pull/466#discussion_r700616088)

Add tls logic to ingress lib chart

---

charts/dsp-argocd/Chart.lock
charts/dsp-argocd/Chart.yaml
charts/dsp-argocd/README.md
charts/dsp-argocd/values.yaml

I'll update the repo sever image tag when this is merged: https://github.com/broadinstitute/terra-helmfile-images/pull/21

DDO-1274 Upgrade to ArgoCD 2.0.5 / Helm chart 3.12.1

---

charts/buffer/Chart.yaml
charts/buffer/templates/ingress/ingress.yaml

Revert buffer ingress chart

---

charts/externalcreds/templates/deployment.yaml
charts/externalcreds/templates/ingress/service.yaml
charts/externalcreds/values.yaml

https://broadworkbench.atlassian.net/browse/POL-51
deployment changes for frontend and backend ECM

POL-51 ECM background processes

---

charts/buffer/README.md
charts/buffer/templates/deployment.yaml

Missed this when I did https://github.com/broadinstitute/terra-helm/pull/455

DDO-1444 Remove use of appVersion from buffer chart

---

charts/dsp-argocd/values.yaml

Very circular ArgoCD image bump. https://github.com/broadinstitute/terra-helmfile-images/pull/22

DDO-1444 Version bump for ArgoCD repo server

---

charts/poc/templates/deployment.yaml

This is GHA workflow testing. I will merge without approval and revert the change in a future PR.

DDO-1530 workflow testing

---

charts/thurloe/templates/podDisruptionBudget.yaml

Add [pod disruption budget ](https://v1-20.docs.kubernetes.io/docs/tasks/run-application/configure-pdb/)to reduce disruption during node pool upgrades This ensures minimum availability is maintained at all times

* DDO-1428 Add PDB to Thurloe

---

charts/rawls/README.md
charts/rawls/templates/_deployment.tpl
charts/rawls/values.yaml

Revert rawls cloudsql proxy 

---

charts/externalcreds/Chart.lock
charts/externalcreds/Chart.yaml
charts/externalcreds/README.md
charts/leonardo/Chart.yaml
charts/leonardo/README.md
charts/poc/Chart.yaml
charts/poc/README.md
charts/terra-cluster/Chart.lock
charts/terra-cluster/Chart.yaml
charts/terra-cluster/README.md
charts/workspacemanager/Chart.lock
charts/workspacemanager/Chart.yaml
charts/workspacemanager/README.md

Revert DDO-1530 / #489 This reverts commit cad91bff2ce272fcac4957a1d57f4a312f9ef2ad.

---

charts/leonardo/templates/deployments/_deployment.tpl

Updates:
Cloudsql proxy to gcr.io/cloudsql-docker/gce-proxy:1.24.0-buster
Moves cloudsql proxy container before application container.
Adds 30 second sleep using post-start.

* DDO-1352 Add 30-second sleep for Leonardo couldSQL proxy

---

charts/ingresslib/Chart.yaml
charts/ingresslib/templates/_backendconfig.yaml
charts/ingresslib/templates/_ingress.yaml

Add keyword and source to Chart.yaml
Add common logic to the backend config template.

Update library chart

---

charts/agora/templates/deployment.yaml

DDO-1530 Noop change: testing chart publishing workflows 

---

charts/agora/templates/deployment.yaml

This reverts commit e4f605833596bf5d252babe65ec04679475fdbee (#508)

Revert "DDO-1530 Noop change: testing GCS chart publishing (#508)"

---

charts/externalcreds/Chart.lock
charts/externalcreds/Chart.yaml
charts/externalcreds/README.md
charts/leonardo/Chart.yaml
charts/leonardo/README.md
charts/poc/Chart.yaml
charts/poc/README.md
charts/terra-cluster/Chart.lock
charts/terra-cluster/Chart.yaml
charts/terra-cluster/README.md
charts/workspacemanager/Chart.lock
charts/workspacemanager/Chart.yaml
charts/workspacemanager/README.md

Previously merged in https://github.com/broadinstitute/terra-helm/pull/489 and then reverted in https://github.com/broadinstitute/terra-helm/pull/498

DDO-1530 Re-enable new GCS repo

---

charts/ingresslib/templates/_backendconfig.yaml
charts/ingresslib/templates/_frontendconfig.yaml
charts/ingresslib/templates/_ingress.yaml
charts/ingresslib/templates/_service.yaml

This PR is to address this [comment](https://github.com/broadinstitute/terra-helm/pull/502/files#r714085722)

Add logic when ingress isn't enabled

---

charts/thurloe/Chart.yaml
charts/thurloe/templates/podDisruptionBudget.yaml

* DDO-1578 Refactor Thurloe to use pdb library

---

charts/buffer/Chart.yaml
charts/buffer/README.md
charts/buffer/templates/deployment.yaml
charts/buffer/templates/podDisruptionBudget.yaml

* DDO-1578  Add pdb to Buffer

---

charts/externalcreds/templates/deployment.yaml
charts/externalcreds/values.yaml

Exposes a value that was already fed into the environment

add ecm googleproject [POL-83]

---

charts/buffer/Chart.yaml
charts/buffer/README.md
charts/buffer/templates/deployment.yaml
charts/buffer/templates/podDisruptionBudget.yaml

Reverts broadinstitute/terra-helm#518

Revert "* DDO-1578  Add pdb to Buffer"

---

charts/externalcreds/templates/deployment.yaml

This may have been breaking our releases, trying to fix it

quote boolean value in deployment.yaml [POL-83]

---

charts/buffer/Chart.yaml
charts/buffer/README.md
charts/buffer/templates/deployment.yaml
charts/buffer/templates/podDisruptionBudget.yaml

This is a second try at adding a PDB to buffer using the PDB library. The last iteration failed due to the added matchLabel to the deployment. When adding new labels it requires us to delete and re-create the deployments. As a workaround, we pass iin the same selectors used in the deployment, buffer.selectors, to the PDB library. This prevents us from re-creating the deployment.

* DDO-1578 Add buffer PDB

---

charts/ingresslib/templates/_ingress.yaml
charts/pdblib/templates/_pdb.yaml

Update name in ingress and pdb library

---

charts/ingresslib/templates/_ingress.yaml
charts/pdblib/templates/_pdb.yaml

Forgot to push last commit to upper case name.

Uppercase the N in .chart.Name

---

charts/agora/Chart.yaml
charts/agora/README.md
charts/agora/templates/ingress.yaml
charts/agora/templates/ingress/backendconfig.yaml
charts/agora/templates/ingress/frontendconfig.yaml
charts/agora/templates/ingress/service.yaml
charts/agora/values.yaml

Refactors Agora's ingress, frontend config, backend config, and service charts to use the ingress library.
[END-DIFF](https://github.com/broadinstitute/terra-helmfile/pull/1759#issuecomment-936998918) of the work done in this PR. [PR](https://github.com/broadinstitute/terra-helmfile/pull/1759) needs to be release with this.

* DDO-1468 Refactor  Agora service to use ingress library

---

charts/firecloudui/Chart.yaml
charts/firecloudui/templates/podDisruptionBudget.yaml

* DDO-1578 Add PDB to Fire Cloud UI

---

charts/consent/templates/podDisruptionBudget.yaml

Fix chart definition for consent PDB

---

charts/ingresslib/templates/_util.tpl

This change was accidentally reverted in a PR.

Switch name reference to .Chart.Name

---

charts/consent/templates/ingress/frontendconfig.yaml

Updates Frontend configs name as seen here: https://github.com/broadinstitute/terra-helm/blob/06cc760ebcc7d81235b772467485836a8976a578/charts/consent/templates/ingress.yaml#L22

Fix name for frontend configs to bring service up

---

charts/buffer/templates/role.yaml
charts/buffer/templates/rolebinding.yaml
charts/buffer/templates/secrets.yaml
charts/buffer/templates/service-account.yaml
charts/leonardo/templates/role.yaml
charts/leonardo/templates/roleBinding.yaml
charts/leonardo/templates/serviceAccount.yaml

Realizing I did these for Rawls and the newer migration attempts but missed some circumstances in Buffer/Leonardo. Falls in the category of "would probably be fine for years" but there's weird ways this issue could manifest, so better to fix and standardize than leave it.

[DDO-1649] Add sync wave annotations

---

charts/opendj/templates/cronjob.yaml
charts/opendj/values.yaml

Changes cronjob time to 6 AM EDT and adds enabled value to values.yaml

[No-ticket4] Change opendj restart cronjob start stime

---

charts/terra-prometheus/Chart.yaml
charts/terra-prometheus/templates/_labels.tpl

DDO-1714  Updating prometheus operator to latest

---

charts/terra-prometheus/README.md
charts/terra-prometheus/templates/tls.yaml
charts/terra-prometheus/values.yaml

DDO-1719 Include full wildcard cert chain in prometheus cert secret

---

charts/testrunnerdashboard/templates/rolebinding.yaml
charts/testrunnerdashboard/values.yaml

Enable trdash workload identity.

---

charts/testrunnerdashboard/templates/ingress/service.yaml

Use custom values for ports.

---

charts/testrunnerdashboard/templates/deployment.yaml
charts/testrunnerdashboard/templates/ingress/cert.yaml
charts/testrunnerdashboard/templates/role.yaml
charts/testrunnerdashboard/templates/rolebinding.yaml
charts/testrunnerdashboard/templates/service-account.yaml
charts/testrunnerdashboard/templates/trdash-namespace.yaml
charts/testrunnerdashboard/values.yaml

Add namespace manifest for trdash.

---

charts/testrunnerdashboard/README.md
charts/testrunnerdashboard/values.yaml

Updated README.

---

charts/testrunnerdashboard/README.md
charts/testrunnerdashboard/templates/deployment.yaml
charts/testrunnerdashboard/templates/ingress/cert.yaml
charts/testrunnerdashboard/templates/role.yaml
charts/testrunnerdashboard/templates/rolebinding.yaml
charts/testrunnerdashboard/templates/trdash-namespace.yaml
charts/testrunnerdashboard/templates/workloadidentity.yaml

Fix indentation.

---

charts/testrunnerdashboard/templates/service-account.yaml

Fix label indentation.

---

charts/testrunnerdashboard/templates/ingress/cert.yaml

Updated certmanager version to match dsp-eng-tools.

---

charts/testrunnerdashboard/templates/ingress/backendconfig.yaml

Updated health check to use POD target port and HTTP protocol.

---

charts/testrunnerdashboard/templates/deployment.yaml
charts/testrunnerdashboard/templates/ingress/backendconfig.yaml
charts/testrunnerdashboard/templates/ingress/service.yaml

Updated target port to 443.

---

charts/dsp-grafana/Chart.yaml
charts/dsp-grafana/README.md
charts/dsp-grafana/templates/configmap.yaml
charts/dsp-grafana/templates/cronjob.yaml
charts/dsp-grafana/templates/secretDefinition.yaml
charts/dsp-grafana/templates/sidecarFacilitation.yaml
charts/dsp-grafana/values.yaml

A week's worth of changes to Grafana. I'll go over this all later, I just sorta want to get another merge in before Thanksgiving.

[DDO-1726] Grafana, Week 2

---

charts/dsp-argocd/values.yaml

Bump ArgoCD image for DDO-1591

DDO-1591 ArgoCD image bump

---

charts/dsp-grafana/Chart.yaml

Just added to 3p via https://github.com/broadinstitute/terra-helmfile/pull/2060

Bump dsp-grafana's grafana subchart version

---

charts/elasticsearch/README.md
charts/elasticsearch/values.yaml

DDO-1819 Mitigate Log4j vulnerability in Terra Elasticsearch

---

charts/elasticsearch/values.yaml

DDO-1819 Elasticsearch Log4j mitigation round 2
