- charts/hydra/Chart.yaml
- charts/hydra/templates/_helpers.tpl
- charts/hydra/templates/deployment.yaml
- charts/hydra/templates/istio-ingress.yaml
- charts/hydra/templates/role.yaml
- charts/hydra/templates/rolebinding.yaml
- charts/hydra/templates/secrets.yaml
- charts/hydra/templates/service-account.yaml
- charts/hydra/templates/service.yaml
- charts/hydra/values.yaml
- charts/icdemo/Chart.yaml
- charts/icdemo/templates/_helpers.tpl
- charts/icdemo/templates/deployment.yaml
- charts/icdemo/templates/istio-ingress.yaml
- charts/icdemo/templates/service.yaml
- charts/icdemo/values.yaml
- charts/identityconcentrator/Chart.yaml
- charts/identityconcentrator/templates/_helpers.tpl
- charts/identityconcentrator/templates/deployment.yaml
- charts/identityconcentrator/templates/istio-ingress.yaml
- charts/identityconcentrator/templates/role.yaml
- charts/identityconcentrator/templates/rolebinding.yaml
- charts/identityconcentrator/templates/secrets.yaml
- charts/identityconcentrator/templates/service-account.yaml
- charts/identityconcentrator/templates/service.yaml
- charts/identityconcentrator/values.yaml
This PR adds Helm charts for the Identity Concentrator and Hydra apps, as well as a test app called icdemo. It replaces resources previously defined with kustomize:
https://github.com/DataBiosphere/identity-concentrator/tree/master/config
https://github.com/DataBiosphere/terra-config/tree/master/yyu/identity-concentrator
Along with this change, the following change to the deployment flow is proposed:
https://docs.google.com/document/d/103d2H6816feTyHDYSQXBVft4pOssdW6dFz-4KSzxs9M/edit?usp=sharing
Additionally, this is a special case since this is a third-party app that we are just building images from and deploying. I propose we adjust our deployment approach as follows:
- [Fork](https://github.com/DataBiosphere/healthcare-federated-access-services) the …
> Add ic, hydra, icdemo charts

- charts/cert-manager/Chart.yaml
Chart-releaser has been failing since this PR got merged: https://github.com/broadinstitute/terra-helm/pull/46
Guess the README update makes it want to release a new version of the chart
> Bump cert-manager version, chart-releaser is being silly

- charts/terra-argocd-env/Chart.yaml
- charts/terra-argocd-env/templates/project.yaml
- charts/terra-argocd-env/values.yaml
Add new value, requireSuitable, to terra-env-argocd chart, that limits edit permissions for applications in the project to users in the Workbench Admins group
> DDO-475 Suitability restrictions on Terra environment projects

- charts/workspacemanager/Chart.yaml
- charts/workspacemanager/templates/_helpers.tpl
- charts/workspacemanager/templates/service.yaml
- charts/workspacemanager/values.yaml
Add new values to the workspacemanager chart:
`serviceFirewallEnable` - set to true to restrict traffic to the service based on source address
`serviceAllowedAddresses` - map of trusted source addresses
`global.trustedAddresses` - optional global map of trusted source addresses, merged with `serviceAllowedAddresses` to create final whitelist
Eg.
```
serviceAllowedAddresses:
broadInternal:
- 69.43.20.2/24
prodRawls:
- 35.1.2.23/32
- 109.5.6.7./32
```
> DDO-476 Firewall restrictions for WSM

- charts/cromwell/Chart.yaml
- charts/cromwell/templates/_deployment.tpl
- charts/cromwell/templates/_service.tpl
- charts/cromwell/templates/deployments.yaml
- charts/cromwell/values.yaml
* Remove hardcoded broad internal IPs from default values -- these will be supplied by terra-helmfile via a global value
* Make it possible to disable a configured deployment by adding a new deployment setting, `enabled`
* More careful handling of `merge`/`mergeOvewrite`, which have [surprising behavior](https://github.com/Masterminds/sprig/issues/188)
> DDO-511 More refactoring

- charts/cromwell/Chart.yaml
- charts/cromwell/templates/_configmap.tpl
- charts/cromwell/templates/_deployment.tpl
- charts/cromwell/templates/config/_logback.xml.tpl
- charts/cromwell/templates/deployments.yaml
Configure cromwell on GKE to use a custom logback.xml that produces single-line JSON log messages.
This is NOT real structured logging, where messages are serialized by the application into JSON. I think that would require an application-side change to, at minimum, pull in libraries from [logback-contrib](https://github.com/qos-ch/logback-contrib/wiki/JSON).
Instead, a Pattern is used to to format the message into a JSON object. Logback's `replace` function is used to escape newlines and double quotes in messages, as well as newlines in exception stacktraces.
> DDO-512 Implement JSON-style logging for Cromwell with a custom logback.xml file

- charts/terra-cluster/Chart.yaml
- charts/terra-cluster/values.yaml
This pr adds the new terra-prometheus chart as a dependency of terra cluster so that it can be managed by argocd.
> DDO-398 Add terra-prometheus as dependency

- charts/terra-cluster/Chart.yaml
- charts/terra-cluster/values.yaml
This pr ensures that when deployed with argocd, prometheus is installing all its resources to the monitoring namespace as desired. ( rather than mixing them between default and monitoring)
GKE also abstracts away some internals and does not make them accessible. These include Etcd, controller-manager, and the scheduler. In the default configuration prometheus will try to discover and scrape these components. Disabling monitoring of these inaccessible components makes the prometheus deployment appear healthy.
> DDO-398 terra cluster dependency prometheus

- charts/terra-cluster/Chart.yaml
- charts/terra-cluster/values.yaml
This fixes an issue with prometheus config parameters in terra-prometheus chart. The issue is described here [here](https://github.com/helm/charts/issues/19147). Both of these values must be either true of false for the chart to install properly. 
This issue was some avoided during the iterative process of deploying prometheus in dev with argo
> Ddo 398 terra cluster dependency prometheus

- charts/cromwell/Chart.yaml
- charts/cromwell/README.md
- charts/cromwell/templates/_configmap.tpl
- charts/cromwell/templates/_deployment.tpl
- charts/cromwell/templates/config/_logback.xml.tpl
- charts/cromwell/templates/deployments.yaml
- charts/cromwell/values.yaml
* Escape tabs in log messages (exception stacktraces have them)
* Automatically restart Cromwell when configmap is changed
* Use helm-docs to generate README.md
> DDO-544 Cromwell chart improvements

- charts/terra-argocd-app/Chart.yaml
- charts/terra-argocd-app/templates/app.yaml
- charts/terra-argocd-app/templates/legacy-configs-app.yaml
- charts/terra-argocd-app/values.yaml
Add some new labels to ArgoCD deployment definitions.
For Terra apps (eg. `cromwell-staging`, `workspacemanager-prod`):
* `type: app` (used to distinguish app deployments from other types)
* `has-legacy-configs: (false|true)` true if this deployment depends on another deployment that pulls configuration from firecloud-develop
* `jenkins-sync-enabled: true` can be overriden in terra-helmfile to stop Jenkins deploys to $ENV from syncing specific apps
For deploys that pull configs from firecloud-develop (eg. `cromwell-configs-staging`)
* `type:  legacy-configs`
* `jenkins-sync-enabled: true`
These labels will be used by Jenkins to trigger ArgoCD syncs. See:
* https://github.com/broadinstitute/jenkins-terra-gke-deploy/pull/1
* https://github.com/broadinstitute/dsp-jenkins/pull/415
> DDO-545 Add labels to support orchestrated syncing

- charts/terra-cluster/Chart.yaml
- charts/terra-cluster/values.yaml
Adds a label to default k8s infrastructure metrics to filter them out from forwarding to stackdriver. This is to avoid overwhleming external metric quotas on stackdriver workspaces and to save $.
> DDO-582 Add label to filter k8s infrastructure metrics from stackdriver

- charts/workspacemanager/Chart.yaml
- charts/workspacemanager/README.md
- charts/workspacemanager/templates/deployment.yaml
- charts/workspacemanager/templates/postgres-init-db-configmap.yaml
- charts/workspacemanager/templates/proxy-apache-httpd-configmap.yaml
- charts/workspacemanager/templates/role.yaml
- charts/workspacemanager/templates/rolebinding.yaml
- charts/workspacemanager/templates/secrets.yaml
- charts/workspacemanager/templates/service-account.yaml
- charts/workspacemanager/templates/service.yaml
- charts/workspacemanager/values.yaml
The main use case for this is for preview environments
> Add option to run ephemeral Postgres deployment instead of using CloudSQL

- charts/crljanitor/Chart.yaml
- charts/crljanitor/templates/secrets.yaml
SA & vault secret added in https://github.com/broadinstitute/terraform-ap-deployments/pull/88.
Manually tested with skaffold, janitor able to start up.
> Use the sqlproxy-sa secret for the Janitor deployments of the cloudsql proxy.

- charts/crljanitor/Chart.yaml
- charts/crljanitor/templates/deployment.yaml
- charts/crljanitor/templates/secrets.yaml
- charts/crljanitor/values.yaml
Those two configs are:
1. CONFIG_BASED_AUTHZ_ENABLED - boolean value to control whether this feature is enabled
2. ADMIN_USER_LIST - List of Janitor admin users
> [PF-9] Add configs in Janitor to support admin user authZ.

- charts/terra-argocd-env/Chart.yaml
- charts/terra-argocd-env/templates/project.yaml
This allows to adjust which service account can trigger deploys based on the requiresSuitability value.
> DDO-694 Migrate Jenkins CI/CD permissions out of ArgoCD Helm chart values and into deploy project settings

- charts/ap-argocd-preinstall/Chart.yaml
- charts/ap-argocd-preinstall/templates/backendconfig.yaml
- charts/ap-argocd-preinstall/templates/certificate.yaml
- charts/ap-argocd-preinstall/templates/psp.yaml
- charts/ap-argocd-preinstall/templates/role.yaml
- charts/ap-argocd-preinstall/templates/roleBinding.yaml
Associate a CloudArmor policy with ArgoCD Ingress using a BackendConfig.
Related:
https://github.com/broadinstitute/terraform-dsp-tools-k8s/pull/11
> DDO-363 Add BackendConfig to ArgoCD namespace

- charts/workspacemanager/Chart.yaml
- charts/workspacemanager/templates/_helpers.tpl
- charts/workspacemanager/templates/deployment.yaml
- charts/workspacemanager/templates/proxy-apache-httpd-configmap.yaml
- charts/workspacemanager/templates/secrets.yaml
- charts/workspacemanager/templates/tcell_configmap.yaml
- charts/workspacemanager/values.yaml
See the [wiki page](https://broadinstitute.atlassian.net/wiki/spaces/GAWB/pages/1589608449/Apache+Proxy) for more background on the proxy.
This adds the configuration and settings to use TCell in Workspace Manager's proxy, to perform LDAP lookups for authorization, and to check OIDC audience whitelists.
Based heavily on existing ctmpl proxy configurations: see [Rawls configuration](https://github.com/broadinstitute/firecloud-develop/blob/dev/base-configs/rawls/site.conf.ctmpl) with [values file](https://github.com/broadinstitute/firecloud-develop/blob/dev/run-context/live/configs/rawls/proxy-compose.yaml.ctmpl).
Corresponding changes for values files are in [this helmfile PR](https://github.com/broadinstitute/terra-helmfile/pull/182)
> [AS-484] Add tcell, LDAP support, ID whitelisting to WM proxy

- charts/workspacemanager/Chart.yaml
- charts/workspacemanager/README.md
- charts/workspacemanager/templates/deployment.yaml
- charts/workspacemanager/values.yaml
This change ensures that the Workspace Manager deployment undergoes a rolling update any time a mounted secret or configMap changes. This addresses the issue of certs not being picked up by the Apache proxy after being issued via cert-manager.
This change leverages our deployment of the [reloader service](https://github.com/stakater/Reloader).
> DDO-685 Add reloader annotation to WSM deployment

- charts/cromwell/Chart.yaml
- charts/cromwell/templates/_deployment.tpl
- release-strategy.json
Update Cromwell liveness/readiness checks so that:
* pod is taken out of service after 60s of failed polling
* pod is restarted after 300s of failed polling
Also use @gmalkov's awesome new workflow to auto-bump the Cromwell chart version in terra-helmfile
> DDO-758 Add liveness check to Cromwell chart

- charts/ontology/Chart.yaml
- charts/ontology/templates/deployment.yaml
- release-strategy.json
In Addition to the existing readiness probe which will prevent an ontology pod from
receiving traffic if the status endpoint is unresponsive, this pr adds a liveness probe.
The liveness probe will automatically restart the ontology container after 5 minutes of status check
failues.
﻿- Add liveness probe
- bump chart version
> DDO-761 Ontology Liveness Probe

- charts/consent/Chart.yaml
- charts/consent/templates/podMonitor.yaml
Update the `Chart.Name` reference. For some reason, even though the key is named `name` with a lower case `n`, [it does not validate correctly](https://github.com/broadinstitute/terra-helmfile/pull/343/checks?check_run_id=1275364642):
```
Error: template: consent/templates/podMonitor.yaml:11:44: executing "consent/templates/podMonitor.yaml" at <.Chart.name>: can't evaluate field name in type interface {}
```
> fix chart name reference

- charts/workspacemanager/Chart.yaml
- charts/workspacemanager/templates/deployment.yaml
- charts/workspacemanager/templates/secrets.yaml
Change the helm for workspace manager to set the new app SA as the default Google SA with environment variable GOOGLE_APPLICATION_CREDENTIALS. This will match other MC Terra services.
This is a backwards compatible change with existing WM deployments: the app SA has a superset of the permissions in the cloud trace SA, including those needed for logging & monitoring in GKE. We also don't modify the cloudtrace SA volume or variables so that existing images can still use it.
Cleanup for the cloudtrace SA is tracked in PF-197.
> PF-152 Use the WM app SA as the default GOOGLE_APPLICATION_CREDENTIALS.

- charts/consent/templates/deployment.yaml
- charts/consent/templates/secrets.yaml
The oidc proxy container has a bunch of files built into the image under `/etc/ssl` the pattern being used previously to mount tls credentials to the proxy container was overwriting the entire contents of `/etc/ssl` This pr adjust the mounting pattern for tls credentials so that they are inserted into the correct paths under `/etc/ssl/` rather than overwriting the entire directory.
> No ticket Fix to /etc/ssl overwrite in consent proxy volume mounts

- charts/leonardo/values.yaml
without quote, `helmfile` is truncating `00` in the beginning of `imageTag`, adding quota seems to fix it.
Rendering locally seems to work
```
- image: "us.gcr.io/broad-dsp-gcr-public/resource-validator:0042368"
```
> add quote for imageTag

- charts/ontology/templates/deployment.yaml
- charts/ontology/templates/secrets.yaml
See also: https://github.com/broadinstitute/terra-helm/pull/169
From that PR:
> The oidc proxy container has a bunch of files built into the image under /etc/ssl the pattern being used previously to mount tls credentials to the proxy container was overwriting the entire contents of /etc/ssl This pr adjust the mounting pattern for tls credentials so that they are inserted into the correct paths under /etc/ssl/ rather than overwriting the entire directory.
> No ticket Fix to /etc/ssl overwrite in ontology proxy volume mounts

- charts/terra-argocd-app/Chart.yaml
- charts/terra-argocd-app/templates/legacy-configs-app.yaml
Make legacy configs app generator work for Sam
> Make legacy configs app generator work for apps that don't have any instance types

- charts/workspacemanager/templates/_helpers.tpl
Currently, the WM proxy audience check assumes that the first portion of an audience (split by "." characters) has a format like "12345678901". However, some valid audiences have a first portion format like "998877665544-abcdefghijkl54321blahblahblah". This check is rejecting valid calls from Rawls.
Current services check that audiences **start with** the whitelisted ids. This change makes WM do the same.
(I'd like to test this more before submitting, I'll bring up the new version in my integration env and we can test against that)
> [AS-524] Fix audience checking assumptions to use startswith

- charts/consent/templates/deployment.yaml
- charts/ontology/templates/deployment.yaml
This pr adjusts the names of k8s containers from the DUOS services so that it is easily identifiable which service 
service the container is associated with in metadata﻿
> (No Ticket) Adjustments to duos helm chart container naming

- charts/leonardo/templates/zombieMonitorCron.yaml
`REPORT_DESTINATION_BUCKET` exists in application.conf now. Hence we don't need this env variable now
> remove unnecessary config

- charts/cromwell/Chart.yaml
- charts/cromwell/README.md
- charts/cromwell/README.md.gotmpl
- charts/cromwell/templates/_deployment.tpl
- charts/cromwell/values.yaml
Add optional `nodeSelector` and `toleration` values to the Cromwell chart so that we can start scheduling Cromwell on its new dedicated node pool.
See https://github.com/broadinstitute/terraform-ap-deployments/pull/140 for background.
> DDO-832 Add optional nodeSelector, toleration values to Cromwell chart

- charts/consent/README.md
- charts/consent/templates/ingress.yaml
- charts/consent/templates/ingressCert.yaml
- charts/consent/templates/service.yaml
- charts/consent/values.yaml
This pr will convert consent from using a kubernetes internal loadbalancer for access to the application
to use GKE ingress as an external https loadbalancer﻿
> DDO-849 consent-gke-ingress

- charts/consent/templates/ingress.yaml
- charts/consent/templates/service.yaml
- release-strategy.json
This pr adds a back end config to the consent ingress 
so that the https loadbalancer health check properly uses
the status endpoint﻿
> DDO-849-2 consent ingress health check

- charts/consent/templates/ingress.yaml
- charts/consent/values.yaml
This pr ensures that the timeout on requests to consents ingress
are configured the same as the gce loadbalancer which is set to 120 seconds﻿
> DDO-849-3 Set timeout on ingress

- charts/rawls/templates/_deployment.tpl
Notice a log message on rawls pod startup that /var/log/gc didn't exist
add a mounted volume to hold rawls gc logs﻿
> [NO TICKET] Add a gc log volume to rawls helm chart

- charts/rawls/templates/_service.tpl
- charts/rawls/templates/ingress.yaml
- charts/rawls/values.yaml
This pr sets up a backend config for the rawls ingress so that the ingress
health check is configured correctly on pods with multiple containers﻿
> DDO-904 rawls ingress health checks

- charts/cromwell/templates/_deployment.tpl
This PR sets Cromwell's [CPU and memory limits](https://learnk8s.io/setting-cpu-memory-limits-requests) equal to its requests.
Previously, Cromwell had no CPU limit and could expand to use all available CPU on the node where it was running, leading to noisy CPU capacity alerts in #workbench-resilience. This PR will restrict it to using only 7 of the 8 available CPUs on each node.
Similarly, this PR sets Cromwell's memory limit to 40 GiB instead of 50 GiB. This means that Cromwell will only be able to use 40 GiB (43 GB) of the available memory on the node, instead of all of the available memory (Cromwell's nodes have 46.5 GiB / 50 GB total memory).
**Background**
Back when we first tried running Cromwell in GKE, we decided to experiment with having limits that were higher than requests; …
> DDO-911 Cromwell chart fix: set requests == limits

- .github/workflows/pr-release.yaml
- .github/workflows/release.yaml
This avoids race conditions when writing to index.yaml while releasing charts
> Add locking to release workflows

- charts/leonardo/templates/deployments/_deployment.tpl
* Bump Leo's app container requests from 8GiB to 9GiB, to more closely match existing vms.
* Use /version for liveness instead of /status, so Leo isn't restarted automatically when Sam goes down
> DDO-939 Leo tweaks

- charts/dsp-argocd/templates/apps/terra-app-generator.yaml
- charts/terra-argocd-app/Chart.yaml
- charts/terra-argocd-app/templates/app.yaml
- charts/terra-argocd-app/values.yaml
* Configure ArgoCD apps to deploy HEAD revision of terra-helmfile by default (previously this was not specified)
* Add a sync window + automated sync policy to terra-app-generator to automatically sync during a 10-minute window every night at 10pm (the nightly perf deploy kicks off at
> DDO-915 Automatically reset all Terra ArgoCD Apps back to master branch of terra-helmfile every night

- charts/workspacemanager/templates/deployment.yaml
- charts/workspacemanager/templates/secrets.yaml
Workspace Manager stopped using a separate service account for cloud tracing in https://github.com/DataBiosphere/terra-workspace-manager/pull/121, but the existing SA credentials were left in for backwards compatibility. 
All environments are now on a version past this change (see https://github.com/broadinstitute/terra-helmfile/pull/789), so it's now safe to remove this from the Helm chart. I'll make a terraform change to remove this SA once this chart change is deployed to all environments.
No helmfile change is necessary as there is no cloudtrace SA specific value, and we continue to use `Values.cloudTraceEnabled`.
> [PF-197] Remove WM references to cloud trace SA

- charts/filebeat/templates/inputConfig.yaml
This is my quick hack to  stop hammering our non prod logit stack. The workspace manager proxy has been sending a ton of logs. As a quick fix I set filebeat to not forward workspace manager logs to kibana. 
Will make a DDO ticket to come up with a better longterm solution. Perhaps a flag so that only legacy(former GCE) apps deployed on k8s forward to kibana
> don't send worspace manager logs to kibana to avoid quota issues

- charts/filebeat/templates/daemonset.yaml
- charts/filebeat/templates/inputConfig.yaml
Even after disabling debug logging for cromiam, the main source of trouble for the logit quota 
since enabaling k8s log forward, we were still getting worryingly close to the quota each day.
After isolating a few causes of this namely the workspace manager proxy being set to debug 
and the leo cron jobs, it is best to just not forward to logit from anything that isn't a part
of gce terra.﻿
> [No ticket] More Logit Quota management

- charts/buffer/README.md
- charts/buffer/values.yaml
- charts/crljanitor/README.md
- charts/crljanitor/values.yaml
- charts/workspacemanager/README.md
- charts/workspacemanager/values.yaml
Letsencrypt sends out warning emails 20 days before expiry, and our cert-manager certs for these charts are currently set to auto-renew 15 days before expiry. Changing that to 30 days to avoid the email spam.
> DDO-963 Update default cert renewal interval

- charts/terra-prometheus/templates/rules/k8sSystemApiServer.yaml
- charts/terra-prometheus/templates/rules/k8sSystemKubelet.yaml
The prometheus operator helm chart creates a number  of alerting rules on the state of the nodes and other kubernetes system internals which are useful. But it doesn't expose the ability to tune those alerting rules. This pr redefines them in our prometheus wrapper chart so that they can be tuned to our use cases.
Also included is a tweak to the `kubeNodeUnreachable` alert which would spam alerts when the nodes received automatic upgrades. However it will be difficult to verify that this work until the next automatic node upgrade happens.
> DDO-1011 More noise reduction in prometheus alerts

- charts/dsp-argocd/templates/backendconfig.yaml
The Jenkins deploy process uses diffs from ArgoCD to identify which applications need a sync. Lately it's been generating errors like this:
```
[ warn]  Failed to pull a diff for consent-prod from argocd, will retry 1 more times
[debug]  $ argocd app diff consent-prod --hard-refresh
time="2021-02-02T21:01:08Z" level=fatal msg="rpc error: code = Unknown desc = POST https://ap-argocd.dsp-devops.broadinstitute.org:443/application.ApplicationService/Get failed with status code 502"
```
I think this is because the diff operation is taking longer than 30s. If it can't generate a diff, the deploy process performs a sync anyway, but these messages are confusing and it would be nice to quiet them.
> Bump backend timeout for ArgoCD's Ingress

- charts/workspacemanager/README.md
- charts/workspacemanager/templates/deployment.yaml
- charts/workspacemanager/templates/secrets.yaml
- charts/workspacemanager/values.yaml
This is used to ensure we only sync secrets if they exist for buffer in the given environment. Not passed to the WSM Service.
> Add back buffer.enabled flag. 

- charts/workspacemanager/templates/ingress/backendconfig.yaml
- charts/workspacemanager/values.yaml
In order to make the security policy a toggle, it must always be specified in the backend 
config manifest and set to "" when a security policy is not desired. Other wise the cloud armor
policy will not be updated properly if the securityPolicy field is removed entirely
See [here](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#removing_the_configuration_specified_in_a_frontendconfig_or_backendconfig) for more info﻿
> DDO-1073 Enable toggle of security policy on ingress

- charts/workspacemanager/templates/deployment.yaml
The workspace.buffer.enabled flag was re-added in #290, but was not exposed to the WSM app. However, WSM also needs this value to handle status dependencies properly (see [PR](https://github.com/DataBiosphere/terra-workspace-manager/pull/227))
> [PF-457] Re-add buffer enabled flag to WSM app config

- charts/filebeat/templates/config.yaml
Multiline stack traces from k8s deployments were being split by line in kibana. This attempts to fix that﻿
> Fix multiline stack trace handling

- charts/elasticsearch/templates/backup/role.yaml
- charts/elasticsearch/templates/backup/roleBinding.yaml
- charts/elasticsearch/templates/backup/serviceAccount.yaml
Last night 3/2/21 The elastic search backup cronjob failed to schedule. I realized I forgot to make a service account for it.
This pr creates a service account for the backup cron to use.﻿
> [No Ticket] Create a Service Account for Elasticsearch backup Cronjob

- charts/terra-prometheus/templates/rules/appRules.yaml
This pr configures an alert which looks at the last time each cronJob was successfully scheduled and compares to the current time. If greater than 24 hours have elapsed since the last successful scheduling, an alert will fire. There is a 2 hour buffer before the alert fires to accommodate for transient timing issues and avoid potential alert spam since most of our cronjobs are daily.﻿
> DDO-1102 Alert if cronjob does not run in 24 hour period

- charts/elasticsearch/templates/backup/cronjob.yaml
I realized that the ES backup cron was failing because curl is not included in the base alpine image. This is a quick fix to that issue. I had trouble finding a minimal base image that actually has `curl` Happy to take other recommendations if any one has them.
> No Ticket Ensure ES backup can use Curl

- charts/elasticsearch/values.yaml
Orchestration expects the name of the elasticsearch it connects to to be `elasticsearch5a`
currently this chart uses the default of `elasticsearch`
﻿
> DDO-1125 Fix Cluster name for GKE Elasticsearch

- charts/buffer/templates/configmaps/proxy-tcell-configmap.yaml
- charts/buffer/templates/deployment.yaml
- charts/buffer/values.yaml
This pr includes fixes so that buffer's apache proxy is able to be properly monitored by tcell, one of the blockers for RBS going to prod.
Changes:
1. Update buffer's proxy to use the latest image `broadinstitute/openidc-proxy:tcell_3_1_0`. This is identical to the previous proxy image other than that it is using the latest version of tcell.
2. Rename the environment variables containing the tcell api key and app id. The latest version of tcell can read these values directly from the environment rather than trying to inject them into the config file as bash variables, which doesn't actually work. [more info](https://docs.tcell.io/docs/server-agent-options#section-environment-variables-and-config-file-properties)
> DDO-1132 Fix Tcell config for Buffer

- charts/leonardo/README.md
- charts/leonardo/templates/deployments/_deployment.tpl
- charts/leonardo/values.yaml
Currently, we've configured Leo with a 5-minute liveness probe. This means that if Leo's `/version` endpoint ever stops responding, after 5 minutes Kubernetes will restart the pod, saving the on-call engineer from being paged and having to restart the pod manually.
This is useful, but poses a problem for Liquibase migrations. Leo's `/version` endpoint does not start returning 200s until Liquibase migrations have finished; in the event a migration takes longer than 5 minutes, Kubernetes will kill the pod and potentially leave the database in a half-migrated state. (See [this thread](https://broadinstitute.slack.com/archives/C01E2DDTGQG/p1615304704000800) from a few weeks ago where the first statement of a migration was executed, but not the second, and I had to manually fix up the database …
> DDO-1147 Add 3-hour startupProbe to Leo

- charts/consent/Chart.yaml
- charts/consent/templates/_consent.yaml.tpl
- charts/consent/templates/deployment.yaml
- charts/ontology/Chart.yaml
- charts/ontology/templates/_ontology.yaml.tpl
- charts/ontology/templates/deployment.yaml
https://broadworkbench.atlassian.net/browse/DUOS-1124
Move the exposed admin endpoint to a different port, `8081`.
TODO: ~Ensure that the new port is not exposed outside the cluster.~ Done.
> DUOS-1124 Move admin endpoints to private port

- charts/jobmanager/Chart.yaml
- charts/jobmanager/README.md
- charts/jobmanager/templates/_labels.tpl
- charts/jobmanager/templates/configmap.yaml
- charts/jobmanager/templates/deployment.yaml
- charts/jobmanager/templates/ingress.yaml
- charts/jobmanager/templates/ingress/backendconfig.yaml
- charts/jobmanager/templates/ingress/frontendconfig.yaml
- charts/jobmanager/templates/ingress/service.yaml
- charts/jobmanager/templates/role.yaml
- charts/jobmanager/templates/rolebinding.yaml
- charts/jobmanager/templates/serviceaccount.yaml
- charts/jobmanager/values.yaml
This is an initial Helm chart implementation for Job Manager, based on its existing docker-compose configs.
Note that:
* Instead of a primary `app` container, Job Manager has two containers: `ui`, and `api`. The `ui` and `api` containers are deployed inside the same pod, because they were deployed on the same VM under docker-compose and we would like to minimize the delta associated with the GKE transition
* The Job Manager vms have 4 CPUs/3.5 GiB of RAM; I have separately given the UI container and API container each 4 CPUs/3.5 GiB of RAM, because it's hard to say which container uses more resources with the data available for GCE vms. Once the containers are running in GKE, Prometheus should give us enough information to allocate resources more efficiently.
* Job Manager has no database …
> DDO-1105 Helm chart for Job Manager

- charts/firecloudorch/templates/deployment.yaml
A mistake in conditional logic caused the new probe helm chart update for orch to fail due to unable to mount a nonexistent volume when the probe was disabled. This fixes that mistake.
> [No Ticket] Fix to failed volume mount when orch probe is disabled

- charts/cromwell/Chart.yaml
- charts/cromwell/README.md
- charts/cromwell/templates/_deployment.tpl
- charts/cromwell/values.yaml
Add a 3-hour startup probe to the Cromwell chart, to prevent the 5-minute liveness probe from disrupting liquibase migrations.
> Add a startup probe to Cromwell chart

- charts/filebeat/templates/inputConfig.yaml
The naming convention for buffer pods was changed somewhat recently. This caused buffer logs to sneak back into kibana, contributing to quota overages. This makes sure buffer logs are not going to kibana﻿
> [No Ticket] Filebeat shouldn't export buffer logs to logit

- charts/leonardo/values.yaml
https://github.com/broadinstitute/terra-helm/pull/359 worked as intended. But somehow argo parsed the hash as `              image: 'us.gcr.io/broad-dsp-gcr-public/zombie-monitor:5.186276e+06'`. Adding double quote and see if this fixes things
> [no ticket] fix hash bump

- charts/dsp-argocd/values.yaml
Bump requests to 4 Gib RAM / 4 CPUs for both repo server and controller containers, which seem to be resource constrained based on graphs in the GCP console. I'm skipping limits for now because I want to leave room for the containers to grow if needed.
> Bump resources on ArgoCD repo server to see if it helps address ArgoCD timeouts & slowness

- charts/dsp-argocd/values.yaml
Follow-up on https://github.com/broadinstitute/terra-helm/pull/366:
Reduce CPU request from 4 to 3.2 so that ArgoCD pods are still schedulable on the dsp-tools cluster's existing node pool.
> DDO-1209 Bump ArgoCD resources

- charts/elasticsearch/templates/backup/cronjob.yaml
- charts/elasticsearch/values.yaml
Installing curl after the image starts was setting off security alarm bells in GCP that were very noisy. Using an image with curl pre-installed﻿
> DDO-1214 Use image with curl baked in to avoid GCP security alerts

- charts/opendj/templates/service.yaml
- charts/opendj/templates/statefulset.yaml
- charts/opendj/values.yaml
This way:
* We have a single location where OpenDJ's container image version is set
* We can match the pattern followed by the other stateful services
> DDO-1261 Remove applicationVersion override for OpenDJ

- charts/opendj/templates/statefulset.yaml
The OnDelete strategy means that someone has to manually delete the OpenDJ pod to trigger a restart. This can lead to unfortunate suprises, for example when I synced OpenDJ in alpha yesterday but the pod didn't actually update. (Props to @mflinn-broad for setting up Prometheus alerts that caught this).
I'm guessing the OnDelete strategy was originally added as a layer of "protection" to prevent automatic OpenDJ restarts; but we already require manual ArgoCD syncs for stateful services, so IMO this layer of protection is unnecessary.
> Switch OpenDJ back to the default rolling update strategy

- charts/dsp-atlantis/Chart.yaml
- charts/dsp-atlantis/templates/azureCredentials.yaml
- charts/dsp-atlantis/values.yaml
This pr adds support for defining secrets holding credentials declaratively via secrets-manager rather than creating them manually. This pr adds support just for managing azure credentials but could easily be extended to support gcp credentials as well. 
Additionally we were previously using an atlantis chart from the now deprecated `helm-stable` chart repo which was deprecated  back in November. I switched the atlantis dependency over to the new atlantis chart repo so that we can actually build new versions of this chart.
> DDO-1268 Define azure credentials for atlantis declaratively

- charts/duos/README.md
- charts/duos/templates/_config.json.tpl
- charts/duos/values.yaml
SCOPE:
Add the metrics api url to the env config and readme
ADDRESSES:
https://broadworkbench.atlassian.net/browse/DUOS-1273
> DUOS-1273[risk=no]Dataset Metrics View - add metrics api url to config

- charts/cromwell/templates/_deployment.tpl
Mount the new config file `cromwell_papi_v2_beta_config.conf` inside the Cromwell pod.
Added here: https://github.com/broadinstitute/firecloud-develop/pull/2556
We're working on making this workflow better, thanks for your patience!
> Mount new Cromwell config file

- charts/cromwell/templates/_deployment.tpl
Please do not merge until after https://github.com/broadinstitute/firecloud-develop/pull/2560 is merged, which in turn should not be merged until the Cromwell 64 release
> Add references config file [BT-303]

- charts/cromiam/templates/ingress/backendconfig.yaml
It seems the `cloud.google.com/v1beta1` BackendConfig version stopped working in `1.19.10-gke.1600`. Google support has asked us to switch to `cloud.google.com/v1`.
I want to verify it works with cromiam first, afterwards I will update all the BackendConfigs
> DDO-1324 Update Cromiam API version

- charts/agora/templates/ingress/backendconfig.yaml
- charts/buffer/templates/ingress/backendconfig.yaml
- charts/consent/templates/ingress.yaml
- charts/duos/templates/ingress/backendConfig.yaml
- charts/externalcreds/templates/ingress/backendconfig.yaml
- charts/firecloudorch/templates/ingress/backendConfig.yaml
- charts/firecloudui/templates/ingress/backendconfig.yaml
- charts/jobmanager/templates/ingress/backendconfig.yaml
- charts/leonardo/templates/ingress/backendconfig.yaml
- charts/rawls/templates/ingress.yaml
- charts/sam/templates/ingress/backendconfig.yaml
- charts/thurloe/templates/ingress/backendconfig.yaml
- charts/workspacemanager/templates/ingress/backendconfig.yaml
- release-strategy.json
I am probably going to disable the chart autoreleaser before merging and then re-enable it with a commit directly to master... Just to avoid all the noise from failed automerges.
> DDO-1324 Set API version to `cloud.google.com/v1` in all BackendConfig manifests

- charts/cromwell/templates/_deployment.tpl
- charts/cromwell/values.yaml
- charts/leonardo/templates/deployments/_deployment.tpl
- charts/leonardo/values.yaml
This PR updates the Cromwell and Leonardo proxy image tag as well as refactoring to pull the image in from values.yaml. 
example:
```
- name: cromwell2-proxy
image: broadinstitute/openidc-proxy:tcell_3_1_0
```
If this is successful, more work will be done to switch all other services over. https://broadworkbench.atlassian.net/browse/DDO-357
> * DDO-1359 Update image tag

- charts/leonardo/Chart.yaml
- charts/leonardo/README.md
- charts/leonardo/templates/migration.yaml
- charts/leonardo/values.yaml
Adds the [liquibase-migration](https://github.com/broadinstitute/terra-helm/tree/master/charts/liquibase-migration) library chart to Leonardo's. Also re-ran the `helm-docs` tool since it seems like no one had run it for a bit.
This won't work--`migration.enabled` shouldn't be set to true anywhere--until https://github.com/broadinstitute/firecloud-develop/pull/2598 has been merged and is in dev. The liquibase-migration chart will expect the liquibase.properties file to already be present in the set of rendered app ctmpl files. 
Once that PR is merged, we can make a terra-helmfile PR with [this diff](https://github.com/broadinstitute/terra-helmfile/compare/DDO-1354-leonardo-liquibase-sync-job) to enable it in dry-run mode for dev (dry-run is defaulted to …
> [DDO-1354] Adding liquibase-migration chart to leonardo's

- charts/leonardo/values.yaml
no-op no longer the default, leonardo charts that explicitly enable liquibase migrations will now also have explicitly change the command if no-op is desired
> [DDO-1355] Use "update" as the liquibase command for real operation

- charts/dsp-argocd/Chart.lock
- charts/dsp-argocd/Chart.yaml
- charts/dsp-argocd/README.md
- charts/dsp-argocd/local-charts/dsp-argocd-notifications/Chart.lock
- charts/dsp-argocd/local-charts/dsp-argocd-notifications/Chart.yaml
- charts/dsp-argocd/local-charts/dsp-argocd-notifications/templates/_labels.tpl
- charts/dsp-argocd/local-charts/dsp-argocd-notifications/templates/psp.yaml
- charts/dsp-argocd/local-charts/dsp-argocd-notifications/templates/role.yaml
- charts/dsp-argocd/local-charts/dsp-argocd-notifications/templates/roleBinding.yaml
- charts/dsp-argocd/local-charts/dsp-argocd-notifications/templates/secrets.yaml
- charts/dsp-argocd/local-charts/dsp-argocd-notifications/values.yaml
- charts/dsp-argocd/templates/apps/terra-app-generator.yaml
* Update the dsp-argocd Helm chart to also deploy [ArgoCD Notifications](https://github.com/argoproj-labs/argocd-notifications) (it's necessary to deploy it in the same namespace where ArgoCD creates Application resources)
* I've configured it in a local subchart instead of an external subchart to save pointless version bump PRs
* Add annotations to the terra-app-generator app to send a Slack notification to #ap-k8s-monitor when a sync fails
> DDO-1409 Deploy ArgoCD Notifications alongside ArgoCD

- charts/opendj/templates/statefulset.yaml
The primary symptom of DDO-1411 is that OpenDJ stops accepting new connections on port 636, so let's adjust OpenDJ's liveness probe to monitor 636 instead of 389.
> DDO-1411 Switch OpenDJ liveness probe to port 636

- charts/dsp-argocd/templates/apps/gha-runner.yaml
- charts/dsp-argocd/templates/projects/dsp-ci.yaml
- charts/dsp-argocd/values.yaml
I rendered these out to yaml and applied them manually before merging the charts, adjusting the version numbers here, and making this PR.
- I think slack notifs on unknown sync state--common for a moment if you're using branches and stuff--would be too noisy, so only alerting on straight failures
- defining project separately so as to not tightly couple dsp-ci (the whole cluster) to gha-runners (since I bet someone is going to ask us to run jenkins nodes here within 3 months)
- self heal is on because that seems neat
> [DDO-1158] Add gha-runner charts to Argo

- charts/sysbox/templates/psp.yaml
Hopefully this will be the only one of these. Helps to name the psp the same as what the role actually references, and of course hostPaths are their own field here.
> [DDO-1424] name sysbox psp correctly, allow host paths

- charts/dsp-argocd/values.yaml
- charts/sysbox/templates/psp.yaml
Last one, because this one is confirmed working at https://ap-argocd.dsp-devops.broadinstitute.org/applications/sysbox. I'll just nuke pods to bump the chart if I have to.
> [DDO-1424] Yet another sysbox psp change

- charts/dsp-argocd/values.yaml
- charts/terra-argocd-app/templates/app.yaml
**Bugfix**: I realized recently that our ArgoCD apps for Terra services were still invoking `helmfile` directly, with selectors, instead of running the `render` script. This PR fixes that:
* Bump ArgoCD image to include the terra-helmfile-app plugin (https://github.com/broadinstitute/terra-helmfile-images/pull/19)
* Update Terra ArgoCD apps to use the terra-helmfile-app plugin
> DDO-1433 Use terra-helmfile-app ArgoCD plugin

- charts/dsp-argocd/values.yaml
Tested that it works by having Helm use 0.3.0 manually. Even if we need to change the image in the future, this pulls nightly of it, and we can override it in the values file in terra-helm-definitions.
> [DDO-1425] Bump gha-runner-instances to use our image

- charts/dsp-argocd/values.yaml
- charts/dsp-gha-runner-instances/templates/runnerDeployments.yaml
What I get for not testing this over the weekend (I'm joking). Found that the runners didn't scale down right over the weekend because of an incomplete refactoring on my part.
> [DDO-1384] Lower number of runner replicas over weekends

- charts/dsp-argocd/values.yaml
Adds an account to Argo CD able to sync wsmtest. I've generated a token for it and fully tested that this works, and that it rejects attempts to do anything else.
```
curl --fail --silent --show-error --location --request POST 'https://ap-argocd.dsp-devops.broadinstitute.org/api/v1/applications/workspacemanager-wsmtest/sync' \
--header "Authorization: Bearer $(vault read -field=token secret/suitable/argocd/local-accounts/low-privileged/wsmtest-sync)" \
| jq .operation
```
> [DDO-1449] Add wsmtest-sync account

- charts/consent/README.md
- charts/consent/templates/deployment.yaml
- charts/consent/values.yaml
Moves cloudsql proxy container before application container. Adds 30 second sleep using post-start. 
Env-dif can be seen [here](https://github.com/broadinstitute/terra-helmfile/pull/1621#issuecomment-910542814).
> * DDO-1352 Add 30-second sleep for Consent couldSQL proxy

- charts/thurloe/README.md
- charts/thurloe/templates/deployment.yaml
Moves cloudsql proxy container before application container. Adds 30 second sleep using post-start.
> * DDO-1352 Add 30-second sleep for Thurloe couldSQL proxy

- charts/buffer/templates/ingress/ingress.yaml
Moving Buffer's ingress out of beta to v1. This has been tested and verified [here](https://console.cloud.google.com/kubernetes/ingress/us-central1-a/terra-qa/buffer-qa-01/buffer-ingress/yaml/view?project=broad-dsde-qa). 
Please note:
`networking.gke.io/v1beta1.FrontendConfig` is now `networking.gke.io/frontend-config `([link](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#associating_frontendconfig_with_your_ingress))
`spec.backend` is renamed to `spec.defaultBackend`
The backend serviceName field is renamed to `service.name`
Numeric backend `servicePort` fields are renamed to `service.port.number`
> Move Buffer ingress to V1

- charts/crljanitor/README.md
- charts/crljanitor/templates/deployment.yaml
- charts/crljanitor/values.yaml
Moves cloudsql proxy container before application container. Adds 30 second sleep using post-start.
Env-dif can be seen [here](https://github.com/broadinstitute/terra-helmfile/pull/1625/checks?check_run_id=3495447673#step:8:348).
> * DDO-1352 Add 30-second sleep for CRL Janitor couldSQL proxy

- .github/workflows/pr-release.yaml
- .github/workflows/release.yaml
- charts/agora/templates/deployment.yaml
Update terra-helm chart-releaser workflows to publish charts to GCS.
Related:
* https://github.com/DataBiosphere/github-actions/pull/29
> DDO-1530 Enable GCS publishing

- charts/rawls/README.md
- charts/rawls/templates/_deployment.tpl
- charts/rawls/values.yaml
Updates:
* Moves cloudsql proxy container before application container.
* Adds 30 second sleep using post-start.
> * DDO-1352 Add 30-second sleep for Rawls couldSQL proxy

- charts/workspacemanager/README.md
- charts/workspacemanager/templates/deployment.yaml
- charts/workspacemanager/values.yaml
Updates:
* Cloudsql proxy to gcr.io/cloudsql-docker/gce-proxy:1.24.0-buster
* Moves cloudsql proxy container before application container.
* Adds 30 second sleep using post-start.
> * DDO-1352 Add 30-second sleep for WSM couldSQL proxy

- charts/agora/Chart.lock
- charts/agora/README.md
- charts/agora/templates/deployment.yaml
- charts/agora/values.yaml
Updates:
* Moves cloudsql proxy container before application container.
* Adds 30 second sleep using post-start.
> * DDO-1352 Add 30-second sleep for Agora couldSQL proxy

- charts/hydra/README.md
- charts/hydra/templates/deployment.yaml
- charts/hydra/values.yaml
Updates:
* Cloudsql proxy to gcr.io/cloudsql-docker/gce-proxy:1.24.0-buster
* Moves cloudsql proxy container before application container.
* Adds 30 second sleep using post-start.
> * DDO-1352 Add 30-second sleep for Hydra couldSQL proxy

- charts/externalcreds/README.md
- charts/externalcreds/templates/deployment.yaml
- charts/externalcreds/values.yaml
Moves cloudsql proxy container before application container. Adds 30 second sleep using post-start.
> * DDO-1352 Add 30-second sleep for ExternalCreds couldSQL proxy

- charts/buffer/Chart.yaml
- charts/buffer/README.md
- charts/buffer/values.yaml
The liquibase-migration helper chart has been reworked and has been tested in dev. This PR adds it to Buffer's chart and the accompanying terra-helmfile PR (https://github.com/broadinstitute/terra-helmfile/pull/1730) will enable the migrations as the updated chart propagates through the release cadence.
For background:
When apps start and block their startup on running possibly-lengthy Liquibase migrations, it is harder to detect and fix actual issues with app startup (in other words, hour-long startups are within the realm of expected behavior, so automated checks need to not fire). 
Our solution is to _also_ run an app's migrations before the app ever starts, using an Argo CD sync hook. We use the app image's own changelogs, liquibase version, JDBC driver, etc. When the app starts, …
> [DDO-1467] Buffer Chart: Add liquibase-migration subchart

- charts/dsp-argocd/values.yaml
- charts/dsp-gha-runner-instances/README.md
- charts/dsp-gha-runner-instances/values.yaml
This'll make runners no longer require sysbox.
**Merge order:** first for DDO-1545 (before #523)
**Post-merge:** deploy the new Argo CD chart version
> [DDO-1545] Remove references to sysbox from runner instances

- charts/pdblib/templates/_pdb.yaml
- charts/pdblib/templates/_util.yaml
PR allows match labels defined in inheriting charts and checks to make sure they're defined.
> [No ticket]Refactor PDB to accept match labels from inheriting charts.

- README.md
- charts/agora/Chart.yaml
- charts/agora/README.md
- charts/buffer/Chart.yaml
- charts/buffer/README.md
- charts/consent/Chart.yaml
- charts/cromiam/Chart.yaml
- charts/duos/Chart.yaml
- charts/firecloudorch/Chart.yaml
- charts/firecloudui/Chart.yaml
- charts/firecloudui/README.md
- charts/jobmanager/Chart.yaml
- charts/jobmanager/README.md
- charts/leonardo/Chart.yaml
- charts/leonardo/README.md
- charts/ontology/Chart.yaml
- charts/rawls/Chart.yaml
- charts/terra-ap-prometheus-operator/install.sh
- charts/terra-argocd-app/README.md
- charts/thurloe/Chart.yaml
- charts/thurloe/README.md
A big mass rename, except for terra-ap-prometheus-operator because the chart doesn't build properly.
I did some poking and that chart references a dependency so old it was deleted. The chart itself doesn't actually change in the renaming, just the helper install.sh that references adding the helm repo
> [DDO-1654] Always reference GCS helm repo

- charts/consent/Chart.yaml
- charts/consent/README.md
- charts/consent/templates/_consent.yaml.tpl
- charts/consent/values.yaml
Partially addresses: https://broadworkbench.atlassian.net/browse/DUOS-1457
Adds a configuration value for sendgrid's status json
~Depends on: https://github.com/broadinstitute/terra-helmfile/pull/1904~
Tested against https://github.com/broadinstitute/terra-helmfile/pull/1910 and it is working as expected.
> DUOS-1457: Add sendGridStatusUrl to chart configs

- charts/sam/templates/deployment.yaml
Ticket: [CA-1373](https://broadworkbench.atlassian.net/browse/CA-1373)
This is the version of `broadinstitute/cloudsqlproxy` that we used on GCE (see [Sam's old docker-compose](https://github.com/broadinstitute/firecloud-develop/blob/ee9ab75d42ffe8405318597f74115093cb8e6e3f/run-context/live/configs/sam/docker-compose.yaml.ctmpl#L39)). Since switching to k8s, Sam has been dropping most of its connections during cloudsql maintenance and not opening new connections once the maintenance is complete. It is unclear whether changing the version of this image will solve the connectivity issue, but it's worth trying.
> [CA-1373] Bump sam cloudsqlproxy version

- charts/dsp-argocd/values.yaml
- charts/dsp-gha-runner-instances/templates/runnerDeployments.yaml
Would help if it knew that weekends were recurring. This scales down runners on the weekends to save money but it only did it once.
> [DDO-1726] Fix a runner typo

- charts/dsp-argocd/values.yaml
the merge action skipped 0.6.0 and went straight to 0.7.0. :(
> [DDO-1726] Reference correct version

- charts/sherlock/README.md
- charts/sherlock/templates/serviceMonitor.yaml
- charts/sherlock/values.yaml
This PR adds a `ServiceMonitor` CRD so that sherlock's `/metrics` endpoint can be scraped by prometheus.
> DDO-1762 Hook sherlock into prometheus/grafana

- charts/calhoun/Chart.yaml
- charts/calhoun/README.md
- charts/calhoun/README.md.gotmpl
- charts/calhoun/templates/_helpers.tpl
- charts/calhoun/templates/configmaps/proxy-apache-httpd-configmap.yaml
- charts/calhoun/templates/configmaps/proxy-tcell-configmap.yaml
- charts/calhoun/templates/deployment.yaml
- charts/calhoun/templates/ingress/backendconfig.yaml
- charts/calhoun/templates/ingress/cert.yaml
- charts/calhoun/templates/ingress/frontendconfig.yaml
- charts/calhoun/templates/ingress/ingress.yaml
- charts/calhoun/templates/ingress/service.yaml
- charts/calhoun/templates/role.yaml
- charts/calhoun/templates/rolebinding.yaml
- charts/calhoun/templates/secrets.yaml
- charts/calhoun/templates/service-account.yaml
- charts/calhoun/values.yaml
JIRA: https://broadworkbench.atlassian.net/browse/IA-2746
Add a helm chart for the calhoun (notebook preview) service.
Friends with: https://github.com/broadinstitute/terra-helmfile/pull/1383
I generally used some MC Terra (e.g. `buffer`) services as a model. Calhoun doesn't have any pre-existing ctmpls in firecloud-develop so it's more of a "new" service than a migration of an old GCE service.
Manually deployed to dev: https://calhoun.dsde-dev.broadinstitute.org/swagger-ui/
> [IA-2746] Add calhoun chart

- charts/dsp-atlantis/README.md
- charts/dsp-atlantis/templates/azureCredentials.yaml
- charts/dsp-atlantis/values.yaml
This PR modifies the azure credentials that get mounted to atlantis pods so that they now use the "real" azure identity (service principal) that atlantis will authenticate as to enable deploying resources to azure via terraform
Associated PRs:
- https://github.com/broadinstitute/terra-helm-definitions/pull/75
- https://github.com/broadinstitute/terraform-dsp-tools-k8s/pull/23
> DDO-1772 Adding support for atlantis to deploy resources to azure
